client_secret: ''
user_agent: ''
client_id: ''
username: ''
password: ''
mod_sub: ''
investing_subs:
- "10xPennyStocks"
- "acorns"
- "AusFinance"
- "Baystreetbets"
- "biotech_stocks"
- "Bogleheads"
- "CanadianInvestor"
- "CLOV"
- "dividends"
- "Daytrading" 
- "Duck_Wrangler"
- "EarningsWhisper"
- "EducatedInvesting"
- "eupersonalfinance"
- "FluentInFinance"
- "Finanzen"
- "Fire"
- "FIREUK"
- "fiaustralia"
- "financialindependence"
- "HENRYfinance"
- "IndianStreetBets"
- "IndiaInvestments"
- "IndianStockMarket"
- "Investing"
- "investing"
- "investing_discussion"
- "investingforbeginners"
- "mauerstrassenwetten"
- "options"
- "pennystocks"
- "personalfinance"
- "PersonalFinanceCanada"
- "RealDayTrading"
- "RentalInvesting"
- "SAVA_stock"
- "RobinHoodPennyStocks"
- "RobinHood"
- "SecurityAnalysis"
- "Shortsqueeze"
- "singaporefi"
- "SNDL"
- "smallstreetbets"
- "SqueezePlays"
- "stocks"
- "Stocks_Picks"
- "StockMarket"
- "stockstobuytoday"
- "StocksAndTrading"
- "SwaggyStocks"
- 'thetagang'
- "UKInvesting"
- "UKPersonalFinance"
- "ValueInvesting"
- "wallstreetbets"
- "wallstreetbets2"
- "Wallstreetbetsnew"
- "WallStreetbetsELITE"
- "weedstocks"